config/routes.rb
TellStories::Application.routes.draw do
  get "welcome/index"
  get "welcome/stories"
  get "welcome/write_a_new_stories"

  root to: 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def stories
  end

  def write_a_new_stories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TellStories</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">

    <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "Stories", welcome_stories_path %></li>
        <li><%= link_to "Write a New Stories", welcome_write_a_new_stories_path %> </li>
    </ul>

<%= yield %>
    
    </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<p>This is the first pasge</p>

app/views/welcome/stories.html.erb
<h1>Stories</h1>
<p>This is the Stories page</p>

app/views/welcome/write_a_new_stories.html.erb
<h1>Write a New Stories</h1>
<p>You can start write your story here</p>